spring.application.name=messaging-service

# This service does not need service discovery
spring.cloud.discovery.enabled=false
eureka.client.enabled=false

# Pull configuration from Spring Cloud Config Server (running at 8088)
spring.config.import=optional:configserver:
spring.cloud.config.uri=http://localhost:8088
